- name: Update 
  hosts: group1
  become: yes
  roles: 
    - roles/MAJ  

- name : Install AdGuard
  become: yes
  hosts: Adguard
  roles:
    - roles/Adguard

- name : Install Uptime Kuma
  become: yes
  hosts: Uptime_Kuma
  roles:
    - roles/Uptime_Kuma

